[build]
  publish = "out"
  command = "npm install && NODE_ENV=production npm run build:static"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://us-central1-gravyty-labs.cloudfunctions.net/api/:splat"
  status = 200
  force = true




